### ISSUE TITLE
DM and Search Results

### ISSUE THREAD

**Issue by wabi88** [ccrsxx/twitter-clone#16]
Hello again,
Wondering how difficult it would be to set up Direct messaging and be able to render search results. 
Is that what the Twitter Bearer Token is used for? I applied for the Twitter developers free API and entered my Bearer Token but it didn’t change anything within the app itself.
Would really appreciate some input on what I might be missing or doing wrong.

Thank you,
Very very amateur builder

**Comment by ccrsxx** [comment]
The DM and search for the project probably shouldn't be that hard. But it will definitely take a pretty long time to implement, 

I'm currently very busy with work and university, even If I work on this project again, I'll pass on the dm and search feature as it takes time to implement. 

Probably a feature that I'd implement in the future is #13, #4, and the notification.

About Twitter Bearer Token, it is used to fetch real-time trending data from the real Twitter API. Sadly, It doesn't work anymore because Elon Musk charge for the trending API now.

Wrote a tweet of the full details [here](https://twitter-clone-ccrsxx.vercel.app/tweet/OglBC9VmlVJmtHw0odS5) on this project lol, if you want to read it.
