### ISSUE TITLE
Cannot read properties of undefined (reading 'createdBy')

### ISSUE THREAD

**Issue by 0x3339** [ccrsxx/twitter-clone#23]
hello , I killed a lot of time and did not solve this problem.
please, help(

TypeError: Cannot read properties of undefined (reading 'createdBy')

src\lib\hooks\useArrayDocument.ts (48:58) @ _callee$

    46 | currentData?.map(async (currentData) => {
    47 |   const user = (
> 48 |     await getDoc(doc(usersCollection, currentData.createdBy))     
    49 |   ).data();
    50 |   return { ...currentData, user };
    51 | })

**Comment by ccrsxx** [comment]
Hmm, seems that you use the hook for the document that doesn't have the createdBy property. Can you give me details of when and where it occurred? also if you have changed something within the project.

**Comment by 0x3339** [comment]
add a post to your bookmarks, and then delete the post and go back to your bookmarks.
I noticed the same problem on your site, but I have a full screen error, and you have only in the console, I didn't change anything in the code

**Comment by Ketchupchh** [comment]
did you set up firebase functions? looks like [normalize-stats.tsx](https://github.com/ccrsxx/twitter-clone/blob/f0e162e02930180db5c05a3df229c4180c891536/functions/src/normalize-stats.ts) deals with this.

**Comment by 0x3339** [comment]
> did you set up firebase functions? looks like [normalize-stats.tsx](https://github.com/ccrsxx/twitter-clone/blob/f0e162e02930180db5c05a3df229c4180c891536/functions/src/normalize-stats.ts) deals with this.

Can I email you my indexes config?

**Comment by ccrsxx** [comment]
I couldn't replicate it on my app. The error you see on my app is just from Twitter API, they disable the trending endpoint on the free plan.

![image](https://github.com/ccrsxx/twitter-clone/assets/55032197/1779aeaa-1285-4b76-aaf8-ec882879fe16)

@Ketchupchh Yeah, that could be probably the reason. Maybe when the bookmark tweet is deleted, since it's without the cloud function it doesn't update the user bookmark. And when you try the fetch the tweets that have been deleted you get `undefined`, that's why you get the error because you try to access the `createdBy` property with undefined.

I will try to debug it when I'm free.

**Comment by 0x3339** [comment]
![Screenshot_1](https://github.com/ccrsxx/twitter-clone/assets/98851278/89693d20-e6a0-48d0-9ae6-4c5259079660)

**Comment by 0x3339** [comment]
![Screenshot_2](https://github.com/ccrsxx/twitter-clone/assets/98851278/dc889fbb-ae80-415b-9b77-3f91c3e7cd02)
my screen

**Comment by ccrsxx** [comment]
@0x3339 Okay, I think I see the problem. Will make a pr today to fix it.

**Comment by ccrsxx** [comment]
@0x3339 The latest commit should fix the issue. Thanks for bringing up the issue!

**Comment by 0x3339** [comment]
you are awesome!
